name: Build ESP8266 Firmware

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build firmware
        run: pio run

      - name: Prepare files
        run: |
          cp .pio/build/nodemcuv2/firmware.bin firmware.bin

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            firmware.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
